### ISSUE TITLE
Create examples of unit testing components

### ISSUE THREAD

**Issue by e-schultz** [angular-redux/store#157]

**Comment by uglow** [comment]
Yes!!!! Even if you create just one test, could it test https://github.com/angular-redux/ng2-redux/blob/master/examples/counter/components/counter.component.ts   please?!!?

**Comment by nrgonzalez777** [comment]
+1, currently trying to figure out how to unit test a component that uses the @select binding. Are there any examples out there yet that just don't have the accompanying write up?

**Comment by obiwan007** [comment]
anything new regarding mocking @select?

**Comment by thomas-lebeau** [comment]
I've been able to find a workaround: 
```
beforeEach(() => {
        const ngRedux: NgRedux<{}> = new NgRedux();

        return TestBed.configureTestingModule({
            providers: [
                MyComponent,
                { provide: NgRedux, useValue: ngRedux.configureStore(rootReducer, {}, [], enhancers) },
            ],
        });
    });
```

**Comment by obiwan007** [comment]
Unfortunately this is somehow crashing my test too.

> null is not an object (evaluating 'this.ngRedux.dispatch') in src/test.ts

Somehow inside my Action the ngStore.dispatch is not set correctly.

**Comment by e-schultz** [comment]
In my unit tests, I've been doing something along the lines of ...

// in a test-utils.ts or something
```js
import { NgRedux } from 'ng2-redux';

export const provideMockRedux = (mockState) => {
  let mockRedux = new NgRedux();
  let mockReducer = (state = mockState, action) => {
    return state;
  };
  mockRedux.configureStore(mockReducer, mockState);
  return mockRedux;
};
```

then in the tests

```js
describe('something', () => {
  it('should do stuff', () => {
    let store = provideMockRedux({mocked: 'state'});
    let myComponent = new SomeComponent();
    // other tests
  });
});
```
If you are using `@select` but not injecting NgRedux into your components - you still need to new up an instance, since under the hood `@select` is looking for a static property on NgRedux for a configured store.

**Comment by e-schultz** [comment]
Example test for a component using `@select` - one way is just newing up the component, another is showing `TestBed`

[repo and test](https://github.com/e-schultz/ng2-redux-unit-test-examples/blob/master/src/app/hello/hello.component.spec.ts)

```ts
import { HelloComponent } from './hello.component';
import { NgRedux } from 'ng2-redux';
import { TestBed, async } from '@angular/core/testing';
let defaultReducer = (state, action) => state;

let provideRedux = (state, reducer = defaultReducer) => {
  let store = new NgRedux();
  store.configureStore(reducer, state);
  return store;
};

describe('the hello component', () => {

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        HelloComponent,
      ],
    });
  });

  /*
    Tests without needing TestBed 
  */

  it('should display the message from the state', () => {
    provideRedux({ message: 'Yup' });
    let component = new HelloComponent();
    component.message$.subscribe(message => {
      expect(message).toEqual('Yup');
    });

  });

  it('should add the values of x and y from the state', () => {
    provideRedux({ message: 'Yup', x: 1, y: 2 });
    let component = new HelloComponent();
    component.ngOnInit();
    expect(component.xy).toEqual(3);
  });

  /*
    Tests using test-bed 
  */
  it('should render title in a h1 tag', async(() => {
    provideRedux({ message: 'Yup', x: 1, y: 2 });
    let fixture = TestBed.createComponent(HelloComponent);
    fixture.detectChanges();
    let compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('p').textContent).toContain('Yup');
    expect(compiled.querySelectorAll('li')[0].textContent).toContain('x - 1');
    expect(compiled.querySelectorAll('li')[1].textContent).toContain('y - 2');
    expect(compiled.querySelectorAll('li')[2].textContent).toContain('xy - 3');

  }));

  it('should respond to changes', () => {
    let reducer = (state, action) => {
      switch (action.type) {
        case 'SET_X':
          return Object.assign({}, state, { x: action.payload });
        case 'SET_Y':
          return Object.assign({}, state, { y: action.payload });
        default:
          return state;
      }
    };

    let store = provideRedux({ message: 'Yup', x: 1, y: 2 }, reducer);
    let fixture = TestBed.createComponent(HelloComponent);
    fixture.detectChanges();
    let compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelectorAll('li')[0].textContent).toContain('x - 1');
    expect(compiled.querySelectorAll('li')[1].textContent).toContain('y - 2');
    expect(compiled.querySelectorAll('li')[2].textContent).toContain('xy - 3');

    store.dispatch({ type: 'SET_X', payload: 2 });
    store.dispatch({ type: 'SET_Y', payload: 3 });

    fixture.detectChanges();

    expect(compiled.querySelectorAll('li')[0].textContent).toContain('x - 2');
    expect(compiled.querySelectorAll('li')[1].textContent).toContain('y - 3');
    expect(compiled.querySelectorAll('li')[2].textContent).toContain('xy - 5');
  });
});

```

**Comment by SethDavenport** [comment]
This should be easier now that I've refactored the example to use the Angular CLI - it sets up all Angular's testing boilerplate for us.

**Comment by SethDavenport** [comment]
Actually if anyone else feelsike making a PR to angular2-starter/example-app with some component tests that would be awesome :)

**Comment by jcperez-ch** [comment]
NgRedux constructor now expects an ngZone... I guess that will change the way you instantiate the Mocked NgRedux, 🚩  Not sure if we should use the Angular TestBed and use NgZone as provider.

**Comment by SethDavenport** [comment]
I started some work to provide TestBed compatible mocks for NgRedux and DevToolsExtension.  Haven't rolled them into the main lib yet, but you can see the code evolving in this PR: https://github.com/angular-redux/example-app/pull/21

**Comment by SethDavenport** [comment]
Finally made some progress on this.

`@angular-redux/store` now exposes a 'testing' module that you can use with Angular's `TestBed`: this module swaps mocked versions of `DevToolsExtension` and `MockNgRedux` into the dependency injection context used by your Jasmin unit tests.

`DevToolsExtension` mock currently doesn't do much. However `MockNgRedux` exposes an API that lets you stub out `NgRedux.select` and `@select` so you can have fine grained control over the selectors upon which your components and services depend.

Here are some quick docs: https://github.com/angular-redux/store/blob/master/docs/intro-tutorial.md#unit-testing-selections

Here's a spec file in the example-app repo that shows this in action: https://github.com/angular-redux/example-app/blob/master/src/app/elephants/elephant-page.container.spec.ts.

**Comment by nithinkrishnan** [comment]
Links are dead.

> Here are some quick docs: https://github.com/angular-redux/store/blob/master/docs/intro-tutorial.md#unit-testing-selections
> 
> Here's a spec file in the example-app repo that shows this in action: https://github.com/angular-redux/example-app/blob/master/src/app/elephants/elephant-page.container.spec.ts.

**Comment by e-schultz** [comment]
https://github.com/angular-redux/example-app/blob/master/src/app/animals/animal/component.spec.ts

I'm going on vacation soon, but I think a way to kill time on my flight might be to improve the docs on this a bit :/

**Comment by Sanderand** [comment]
Here's the file the dead link from above was pointing to. It actually works :1st_place_medal: 
https://github.com/angular-redux/store/blob/a8169bd893078464b1b4a8295f1bcadf50f1f9de/docs/intro-tutorial.md

**Comment by surfermicha** [comment]
The solution of @e-schultz  for testing selection with and without Testbed is very nice but based on the deprecated ng2-redux library. How to do that in  angular-redux-store?
