### ISSUE TITLE
anyway to apply observables modifiers inside the decorator?

### ISSUE THREAD

**Issue by born2net** [angular-redux/store#269]
anyway to apply observables functions inside the decorator?

Something like:
```
@select('counter')
setCounter(obs$) {
    this._obs$ = obs$;
    this._obs$.map(e => e)
}
```

tried this with no luck

```
@select(state => state.counter)
  setCounter(obs$) {
    this._obs$ = obs$;
    this._obs$.map(e => e);
  }
```

this to  me would be the killer feature of this lib, as I could take advantage of the observales functions without having to put code into my controller...

regards

Sean

**Comment by SethDavenport** [comment]
Can you clarify what you're hoping to accomplish? Looks like you're applying the `@select` decorator to a function, but that's not supported.  `@select` takes a property and replaces it with an observable that's hooked up the store.

**Comment by SethDavenport** [comment]
Or are you trying to apply arbitrary RxJS logic to the result of `@select`?

**Comment by born2net** [comment]
Yes I understand how it works thanks..
 I would love to be able to apply operators directly under  the decorator, thus never needing to use the observable inside the constructor for further operations

**Comment by born2net** [comment]
exactly.. That would be the killer application for this library

**Comment by born2net** [comment]
I recommend same implemetation as a ng2 input setter:
```
@Input()
    set setAdnetPackageModels(i_adnetPackageModels: List<AdnetPackageModel>) {
        this.adnetPackageModels = i_adnetPackageModels;
    }
```
but for Observabels so we can apply operators without having to be forced to use constructor or ngOnInit

tx

Sean

**Comment by nzjoel1234** [comment]
Not sure if this is related but I would like to be able to do something like this:

I have this in my store:
store.entities.clients.[clientId].[client]

When viewing a client detail page I am getting the client Id from the URL and would like to use the @select decorator to populate a client$ observable. The problem is that the clientId is provided as an observable, so could there be a way were I write a function to pass to @select to select the client object by id from my store.

**Comment by SethDavenport** [comment]
Hmm makes sense - of course anytime we try anything fancy with decorators we get burned by AoT.  Might be able to do something for v5.

**Comment by born2net** [comment]
ya that would be awesome if it supported it

**Comment by born2net** [comment]
I am wondering if there is any progress on this? as this would be awesome!!!
```
@select(['sample_reducer','general'])
    set setGeneral(i_obs$) {
        this._obs$ = i_obs$;
        this._obs$.map(e => 'foo');
    }
```

but since its not supported, I dont think there is anyway I could skip 1 unless I

**Comment by SethDavenport** [comment]
Sorry @born2net this has not been on my priority list. If you feel like taking a stab at it I'd be willing to review a PR.

**Comment by born2net** [comment]
no worries
tx again

**Comment by SethDavenport** [comment]
Thinking about this a little more.  Not sure how I feel about manipulating a given setter function: too many boundary cases in the syntax.

How would you feel about another argument to `@select` which allows you to apply a custom RxJS operator chain?

I'm thinking something like this (based on your example above):

```typescript
export const operator = obs$ => obs$
  .skip(3)
  .map(e => e + 1);
};

class FooBarComponent {
  @selectX(['foo', 'bar'], myOperator) thirdBarPlusOne$;
}
```

**Comment by SethDavenport** [comment]
The reason I've tentatively called it `selectX` is that this is a departure from the existing signature of `@select`, which is currently `@select(selector, comparator)`.  SelectX is terrible, I'd need to either come up with a way to make `@select` more general or a better name.

**Comment by SethDavenport** [comment]
I also like the fact that this encourages you to keep the operator pure.

**Comment by SethDavenport** [comment]
Alternately, we could simply generalize the definition of `selector` (the first argument to `@select`) to include a function that takes an observable.  Currently, a selector can be:

* A property name
* A list of property names (interpreted as a path)
* A function that takes the current state as a scalar and returns a value

Here we would add an additional selector type which would be a function that gets the observalbe store and returns an observable.  So you could do:

```typescript
export const mySelector = store$ => store$
  .pluck('foo', 'bar')
  .skip(3)
  .map(e => e + 1);

class FooBarComponent {
  @select(mySelector) thirdBarPlusOne$;
}
```

**Comment by SethDavenport** [comment]
Note that in both cases, I've chosen to export my operator/selector as a standalone function; this is sadly a requirement for AoT to work.

**Comment by SethDavenport** [comment]
@born2net  @kosz  @e-schultz thoughts?

**Comment by born2net** [comment]
absolutely, that would be a killer feature...!!!!
the function can also be inlined...
that would be sweet
