### ISSUE TITLE
`readonly` modifier for state interfaces in examples

### ISSUE THREAD

**Issue by jiayihu** [angular-redux/store#306]
I think marking state interfaces with `readonly` modifier in counter example would help ensuring immutability and making it more explicit for anyone not very familiar with `redux`. 
What are your thoughts about it?

**Comment by SethDavenport** [comment]
To be honest I haven't really played with it.  It's worth a try.

**Comment by SethDavenport** [comment]
I've added this to our examples.  Thanks for the suggestion, it's a good one!
