### ISSUE TITLE
Error when trying to instantiate a mock instance of NgRedux for unit testing

### ISSUE THREAD

**Issue by ttmarek** [angular-redux/store#329]
I'm trying to test a service that takes in an instance of NgRedux:

```js
@Injectable()
export class SomeService {
  constructor(private ngRedux: NgRedux<IAppState>) {}
}
```

In my tests I've tried mocking out `NgRedux` as follows: 

```js
const mockRedux = {
   dispatch(action) {},
   configureStore() {},
   select() {
    return Observable.from('test');
  },
};

const someService = new SomeService(mockRedux as NgRedux<IAppState>); // line 30
```

But, my tests fail to compile with the following error:

```
ERROR in [default] /path/to/some-service.test.ts:30:58
                                                                                      
Type '{ dispatch(action: any): void; configureStore(): void; select(): Observable<string>; }' cannot be converted to type 'NgRedux<IAppState>'.   
                                             
Property 'ngZone' is missing in type '{ dispatch(action: any): void; configureStore(): void; select(): Observable<string>; }'.
```

Is there a way to easily mock out the store for these kinds of tests?

**Comment by jiayihu** [comment]
I'm currently using the following mock in my tests, inspired by how tests are created in this repository itself:

```typescript
import { NgZone } from '@angular/core';
import { NgRedux as Store } from '@angular-redux/store';
const defaultReducer = (state, action) => state;

class MockNgZone {
  run(fn) {
    return fn();
  }
}

export function configureStore(state, reducer = defaultReducer) {
  const store = new Store(new MockNgZone() as NgZone);
  store.configureStore(reducer, state);
  return store;
}
```

Also see related https://github.com/angular-redux/store/issues/157

**Comment by e-schultz** [comment]
Hi,

What I tend to do is basically 'TypeScript shutup!' - define my mock as `any` and then when passing it into a class - casting it to the type. This works for lots of things. Example:

```js
const mockRedux:any = { // explicitly saying any here is important
   dispatch(action) {},
   configureStore() {},
   select() {
    return Observable.from('test');
  },
}

const someService = new SomeService(mockRedux as NgRedux<IAppState>); 
```

This pattern is also useful for mocking out Http and not jumping through the hoops of Angular Http testing utilities.

```js
let mockHttp:any = {
   get: ()=> Observable.of(myMockResponse)
}

let service = new ServiceThatNeedsHttp(mockHttp as Http)
```

**Comment by SethDavenport** [comment]
I wonder if it's worth exposting an NgReduxTestModule like some of the angular packages (router etc.) do.

**Comment by kenperregaux** [comment]
@e-schultz I tried your example and I get the following error...
 Can't resolve all parameters for NgRedux

@SethDavenport Is NgReduxTestModule in the works? Also, about a year ago you posted on a similar question using ng2-redux and a 'provider' I don't see 'provider' in the new angular-redux is there another way?

**Comment by SethDavenport** [comment]
NgReduxTestModule is indeed in the works. Hopefully I will get it out the door soon.

**Comment by SethDavenport** [comment]
`@angular-redux/store` now exposes a 'testing' module that you can use with Angular's `TestBed`: this module swaps mocked versions of `DevToolsExtension` and `MockNgRedux` into the dependency injection context used by your Jasmin unit tests.

`DevToolsExtension` mock currently doesn't do much. However `MockNgRedux` exposes an API that lets you stub out `NgRedux.select` and `@select` so you can have fine grained control over the selectors upon which your components and services depend.

Here are some quick docs: https://github.com/angular-redux/store/blob/master/docs/intro-tutorial.md#unit-testing-selections

Here's a spec file in the example-app repo that shows this in action: https://github.com/angular-redux/example-app/blob/master/src/app/elephants/elephant-page.container.spec.ts.

**Comment by sebastiangug** [comment]
@SethDavenport  -- the attached docs for testing are 404's now. Any chance you could point me to the new documentation for testing this redux package? I've been struggling all day to find anything of help regarding this.

Thank you.
