### ISSUE TITLE
select decorator and AoT

### ISSUE THREAD

**Issue by Shiroh1ge** [angular-redux/store#333]
Hello, I recently started using redux and I love it! Thank you for the great work on this implementation. I read past issues about the select decorator and it seems to be fixed in Angular CLI, someone else said that it should not have any problems when using `ngc`, but I just tried to use it and got the `"Function calls are not supported"` when compiling in AoT. I tried updating my npm packages, currently on `Angular 4.0.0-beta.8 / redux 6.0.0 / rxjs 5.0.2`, but no luck.  I'm fine with using the explicit approach, but would love if I could make the decorator work, seems much cleaner. Any help is appreciated!

**Comment by SethDavenport** [comment]
Hey - thanks for the kind words.

`@select` is supported with AoT, the Angular-CLI folks implemented a fix for this a few weeks ago.

The error you're getting is most likely related to the Angular AoT compiler's weak support for dynamic constructs in JavaScript. Can you paste the snippet of code that's giving you the issue?

As an aside, you might find this helpful: https://github.com/rangle/angular-2-aot-sandbox

It was put together by a colleague of mine to help flush out things that won't AoT.

**Comment by Shiroh1ge** [comment]
This is what I have in my component:
```
    @select(state => state.counter.counter)counter$:Observable<number>;
    constructor(private redux: NgRedux<AppState>, public counterActions: CounterActions) {
    }

    increment() {
        this.counterActions.increment();
    }

    decrement() {
        this.counterActions.decrement();
    }

```
```
    <button (click)="decrement()" class="btn btn-default">Counter-</button>
    <button (click)="increment()" class="btn btn-default">Counter+</button>

    <div>Count: {{ counter$ | async }}</div>
```
My reducer:
```
export const counterInitialState: CounterState = {
    counter: 0
};

export function counterReducer(state: CounterState = counterInitialState, action: Action): CounterState {
    switch (action.type) {
        case CounterActions.INCREMENT:
            return {counter: state.counter + 1};
        case CounterActions.DECREMENT:
            return {counter: state.counter - 1};
    }
    return state;
}

```
Btw, can you confirm if I'm doing it right? I'm just starting. Feels kind of weird to call counter twice to access the counter value, I'm using the combineReducers to set up the counter reducer,so if I use state.counter I get [object Object] in the view

**Comment by SethDavenport** [comment]
Yeah OK.  The error you're getting is because AoT can't handle the arrow function in

```typescript
@select(state => state.counter.counter)
```

You can verify this by trying the following:

```typescript
export function counterSelector(state) {
  return state.counter.counter
}

// inside your class:
  @select(counterSelector) counter$: Observable<number>
```

This is a pattern I often use when I need non-trivial transformations as the argument to `@select`; in those cases I might even export my selectorFunctions from their own file and combine them with something like [reselect](https://github.com/reactjs/reselect) for performance.

However in your case that would probably be overkill :)

I will come back with a simpler solution once I tackle your second question.

**Comment by SethDavenport** [comment]
So for your second question, about the `counter.counter`, yeah that's awkward.  I suspect you're doing something like this:

```typescript
combineReducers({
  counter: counterReducer,
  otherStuff: otherStuffReducer,
}
```

This will result in a store that's shaped like this:

```typescript
{
  counter: // whatever counterReducer returns
  otherStuff: // whatever otherStuffReducer returns
}
```

Now, your counter reducer also returns an object with a counter property.  So your store ends up looking like:

```typescript
{
  counter: { counter: 0 },
  otherStuff:  // whatever otherStuffReducer returns,
}
```

For example, if you were to change your counter reducer to this:

```typescript
export const counterInitialState: CounterState = {
    foo: 0 // <- I renamed this to 'foo'
};

export function counterReducer(state: CounterState = counterInitialState, action: Action): CounterState {
    switch (action.type) {
        case CounterActions.INCREMENT:
            return {foo: state.foo + 1};
        case CounterActions.DECREMENT:
            return {foo: state.foo - 1};
    }
    return state;
}
```

At this point your store would be shaped like this:

```typescript
{
  counter: { foo: 0 }, // 'counter' comes from combineReducers, 'foo' comes from counterReducer
  otherStuff:  // whatever otherStuffReducer returns,
}
```

And you could access the observable using `@select(['counter', 'foo'])`.

**Comment by SethDavenport** [comment]
However, in this case, I would actually change the reducer to this:

```typescript
export const counterInitialState: number = 0;

export function counterReducer(state: CounterState = counterInitialState, action: Action): CounterState {
    switch (action.type) {
        case CounterActions.INCREMENT:
            return state + 1;
        case CounterActions.DECREMENT:
            return state- 1;
    }
    return state;
}
```
 
And select it with this:

```typescript
@select('counter') counter$: Observable<number>
```

Or, even simpler, if you call `@select` with no arguments it will infer the state property from the variable name. So you can do:

```typescript
@select() counter$: Observable<number> // the $ is ignored by the decorator.
```

**Comment by SethDavenport** [comment]
Hope this helps.

**Comment by Shiroh1ge** [comment]
Thanks for the thorough explanations! You've answered a lot of questions that I had without even asking them.
 The problem was indeed in the arrow function regarding AoT, I will use some different pattern for accessing the store, it's nice that there are a lot of options.
