### ISSUE TITLE
Question: how to turn localStorage using off?

### ISSUE THREAD

**Issue by alsh76** [angular-redux/store#334]
I have noticed the counter example (as well as my boilerplate app) is using `localStorage` to keep current state. Is that really necessary?  

Possible issues with `localStorage`:

1.  limited capacity. My webapp loads big amount of json data. localStorage is restricted by 5Mb. What happens if store size is getting greater than 5Mb?  

2. I see it uses only one key `"angular2-redux-seed"`. What happens if 2 tabs with same app and different data are opened? 

3. When a user reloads the app page it tries to load previous state. It looks like unexpected behaviour and can lead to bugs 

So my question if `localStorage` isn't necessary for this redux implementation how to remove that from  the app code?

**Comment by alsh76** [comment]
ok, I have found how to remove it. By removing `enhancers` from `ngRedux.configureStore` params. But still wondering should I use it if I do not need to load recent state on reload?

**Comment by e-schultz** [comment]
If you don't have the need for it - it's safe to remove. 

In applications that might need to persist to local storage - it might be a small slice of state, not the entire state that gets persisted (ie: maybe API/auth keys, etc)  - and not the entire application state.

**Comment by SethDavenport** [comment]
@alsh76 yeah we threw that into the app as an example of some of the things community Redux enhancers/middlewares can do for you. It's completely optional. It's also configurable to only persist parts of the store if that's something you want.
