### ISSUE TITLE
AOT build fails to resolve @select(anonymous function) static symbol

### ISSUE THREAD

**Issue by 2goatduo** [angular-redux/store#339]
AOT build fails when JIT build does not.  There error reports:

> Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

and pinpoints the following kind of line:

`@select(state => state.foo.bar) foobar$;`

Replacing that line with the following causes the AOT build to succeed:

`@select(['foo', 'bar']) foobar$`

@angular-redux/store  6.0.1
@angular/compiler       2.4.7
@angular/cli        1.0.0-beta.32.3
typescript             2.0.10

**Comment by dagstuan** [comment]
As the compiler error says, this is a limitation with `ngc`, not with `@angular-redux/store`. So this issue should be raised with the angular developers, not with @angular-redux :)

**Comment by Shiroh1ge** [comment]
See this: #333

**Comment by SethDavenport** [comment]
Dag is right - this is an ngc limitation. AoT can't handle arrow functions, only exported names functions.

**Comment by Kevin-Deason** [comment]
Then maybe update your documentation as it doesn't work as advertised with the latest version of ngc https://github.com/angular-redux/store/blob/master/docs/select-pattern.md
