### ISSUE TITLE
ngRedux.subscribe will throw error if store is not configured yet

### ISSUE THREAD

**Issue by peacatshoe** [angular-redux/store#344]
Subscribing to the store with the `ngRedux.subscribe` method will fail if the store is not configured yet (since the `_store` is not set yet).
Since there is a behaviorsubject keeping track of the store (`_store$`), we could subscribe to it and bind the listener once the store is configured. The only problem is unsubscribing from the store is broken.

```
subscribe = (listener: () => void) => {
    if (!this._store) {
        const subscription = this._store$.subscribe(store => {
            if (store) {
                store.subscribe(listener);

                subscription.unsubscribe();
            }
        });

        // need to return the store subscription here somehow
    }

    return this._store.subscribe(listener);
};
```

Do you see any solutions or is it an option to expose the `_store$` so I can subscribe manually?

Some context:
I'm writing a localstorage module that syncs the state to the browser storage. I wrapped this in an enhancer that takes some selectors (much like the selectors in this module) and subscribes to store change events to update the storage. Since the enhancer is triggered before the configureStore is executed, it crashes when trying to subscribe to the _store.
Right now, I'm checking wether _store is defined and subscribe to _store$ to delay my subscription so it won't throw an error. But I'd rather not be accessing any private properties.
Maybe there is a better solution?

**Comment by SethDavenport** [comment]
Sorry for the delay on this.

A couple of notes:

1. you can get access to `_store$` using `select` with no params (e.g. `ngRedux.select()`). This will give you an Observable of the entire root state.
2. `ngRedux.subscribe` and `ngRedux.select().subscribe` are subtly different.

`ngRedux.subscribe` calls straight through to Redux's `store.subscribe`, which manipulates Redux's internal set of listener functions.

`ngRedux.select().subscribe` actually calls `Observable.subscribe()` on the `Observable` returned by `select`.

**Comment by SethDavenport** [comment]
Not 100% sure what your enhancer does, but I think what you want to do is

```typescript
ngRedux.select().subscribe(
  successHandler,
  errorHandler,
  completionHandler)
```

**Comment by SethDavenport** [comment]
It's also worth noting that there are a few existing redux enhancers/middlewares that sync to localstorage already.  redux-localstorage is a decent example.

**Comment by peacatshoe** [comment]
The enhancer syncs the localstorage and the state, and allows specifying specific paths to sync using the same syntax this package uses. I would show some code but it's not open source (might rebuild it as a proper plugin and opensource it someday).

I was able to do it by subscribing to `ngRedux.select()` with a `filter` and `first` to assure the store is there, thanks for the tip!

**Comment by SethDavenport** [comment]
Cool, glad it helped.
