### ISSUE TITLE
Allow angular-redux to work with ng4

### ISSUE THREAD

**Issue by mircowidmer** [angular-redux/store#349]
When I try to `npm install` an ng4 project (4.0.0-rc.6 or 4.0.0) that is using @angular-redux/store@6.0.1, I get the following warning:

> warning "@angular-redux/store@6.0.1" has incorrect peer dependency "@angular/core@^2.4.0".

I believe that is because version 6.0.1 of @angular-redux/store wants an ng2.x.x version, see package.json:

> "@angular/core": "^2.4.0"

**Comment by jvbianchi** [comment]
The same happens with angular 4 final

**Comment by kchojhu** [comment]
+1 for this effort

**Comment by AlainD-** [comment]
Hi,
I suppose it will come soon since Angular 4.0.0 is now out.

**Comment by SethDavenport** [comment]
Yup, we're working on it :)

**Comment by SethDavenport** [comment]
OK - Here's the current progress:

* angular-redux/store: PR: #352, you can try it out by installing @angular-redux/store@6.1.0-alpha.1
* angular-redux/router: PR: angular-redux/router#8, you can try it out by installing @angular-redux/router@6.1.0-alpha.0
* angular-redux/form: still working out a few incompatibilities.
* angular-redux/example-app: waiting for angular-redux/form to be sorted out.

If you're not using angular-redux/form, feel free to try out 6.1.0-alpha (pin your versions). Once I have all three packages updated and working in tandem, I'll release 6.1.0 for real with Angular 4 support.

**Comment by SethDavenport** [comment]
angular-redux/form sorted out. Will update the example app and publish tonight.

**Comment by SethDavenport** [comment]
6.1.0 officially released to npm with angular 4 support. Example app has been updated to use the new packages.
