### ISSUE TITLE
@select anonymous function notation triggers so frequently

### ISSUE THREAD

**Issue by paramsinghvc** [angular-redux/store#358]
```
    @select(state => state.ticketDetails.getIn(['notifications', 'facebook'])
        .update(notifications => {
            return notifications;
            // let feedsSize = notifications.getIn(['feed', 'list']).size;
            // let dmSize = notifications.getIn(['dm', 'list']).size;
            // let date = +(new Date());
            // let notifs = List();
            // if (dmSize > 0) {
            //     notifs = notifs.push(Map({
            //         message: `${dmSize} new message${dmSize > 1 ? 's' : ''}`,
            //         timestamp: date
            //     }));
            // }
            // if (feedsSize > 0) {
            //     notifs = notifs.push(Map({
            //         message: `$ {feedsSize} new mention${feedsSize > 1 ? 's' : ''}`,
            //         timestamp: date
            //     }));
            // }
            // return fromJS({
            //     notifications: notifs,
            //     count: feedsSize + dmSize
            // });
        })) fbNotifications: Observable<any>;
```

I'm trying to listen to a piece of my state using this way, and subscribing to it as 
```
 ngOnInit() {
        this.fbNotifications.subscribe((data) => {
            console.log(data);
        });
    }
```

The problem is that this log is triggering so frequently. Apparently, it listens to all the events happening on the state and not specifically at that path of `notifications, facebook`. It's evident from the fact that when I switch to this notation

`@select(['ticketDetails', 'notifications', 'facebook']) fbNotifications: Observable<any>`

it triggers only once.

The former case is very useful but takes a heavy toll on performance, isn't there a way to achieve the same in a better way or am I messing up with something?

<img width="1278" alt="screen shot 2017-04-09 at 11 47 56 pm" src="https://cloud.githubusercontent.com/assets/4329912/24839816/02a69d34-1d7f-11e7-9004-9a8d13a16c7e.png">

**Comment by e-schultz** [comment]
`@select` will be called every time there is a change in state - the subscribers to it will get notified when the result of that changes.  

One thing to be mindful of when using functions in `@select` - especially if the result is doing something like `fromJS` - it will be getting a new object every time - even if the values haven't changed. 

If you are wanting to do complex calculations/transformations - it'd be better to select the paths with something like

```js
@select(['x','y','a']) a$;
@select(['x','y','b']) b$;
computed$ = a$.combineWithLatest(b$,(a,b)=>.....)
```

or using reselect to create your selectors.

You can also pass in a custom compare function as a second argument,

```js

@select(state=>immutable.stuff.getIn(....),Immutable.is)
@select(state=>immutable.stuff.getIn(....),function(a,b){ 
console.log('is a really the same as b?', a===b)
});
