### ISSUE TITLE
Clean install of latest version 6.2 doesn't work

### ISSUE THREAD

**Issue by abductedMind** [angular-redux/store#376]
### This is a...

* [ ] feature request
* [x ] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [ ] @angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [x ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 6.10.2
Typescript Version: 2.1
Angular Version: 2.6
@angular-redux/store version: 6.2
@angular/cli version: (if applicable)
OS: Test on both Windows AND MacOS - all else was the same reported issue occurred on both system.

### Expected Behaviour:
Entire dependency installs, with all required files.

### Actual Behaviour:
Missing files (or moved files?) when installing version ^6.2 cleanly (from scratch).

Why I discovered this today?: Files are not missing if you install 6.1 and then upgrade to 6.2 (if the repo/app is running and the files remain in use so are not removed)

### Stack Trace/Error Message:
error: Server Error:
error: Error: ENOENT: no such file or directory, stat '...\node_modules\@angular-redux\store\lib\index.js'
    at Error (native)

### Additional Notes:
I discovered this by moving to a new dev env. The original was working and the new location did not. Once issue was discovered and I deleted the dependency folder in node_modules and reinstalled they both failed. Downgrading to 6.1 fixed the problem.

**Comment by abductedMind** [comment]
This was a configuration issue.

**Comment by abductedMind** [comment]
Further investigation yielded that a system.js configuration required a CHANGE to point to /lib/src/index.js rather than /lib/index.js because this file moved. I plan to move to WebPack/AngularCLI so for me this would be a non-issue in the future but others using system.js will have hiccup.

**Comment by SethDavenport** [comment]
Oops should have mentioned that in the changelog.  We have a system-js-example under the anguar-redux github org which I did remember to update.
