### ISSUE TITLE
Dispatch accepting functions

### ISSUE THREAD

**Issue by tt9** [angular-redux/store#386]
### This is a...

* [X] feature request
* [ ] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [X] `@angular/cli`
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

###

Can we get the dispatch method in the NgRedux class to accept a function type? I am using it with redux-thunk and I have to throw an `<any>` cast in front of thunk dispatches to allow it to compile.

**Comment by SethDavenport** [comment]
Yup - a few people have reported this. I have a fix incoming.

**Comment by SethDavenport** [comment]
Fix is available in 6.3.0.
