### ISSUE TITLE
Application doesn't connect to redux devtools when inside an iframe.

### ISSUE THREAD

**Issue by PolarbearDK** [angular-redux/store#388]
### This is a...

* [ ] feature request
* [x ] bug report
* [ ] usage question

### Link to repo showing the issue
your sample app:  https://github.com/angular-redux/example-app

### Expected Behaviour:
See actions in redux devtools even when inside an iframe like:
```<iframe src="http://localhost:4200" />```

### Actual Behaviour:
application doesnt connec to redux devtools when inside an iframe.

### Additional Notes:
it is not an issue with devtools as this works: 
```<iframe src="http://zalmoxisus.github.io/examples/counter/" />```
Also see: https://github.com/zalmoxisus/redux-devtools-extension/issues/357

**Comment by SethDavenport** [comment]
Hi - sorry for the delay on this.

I took a look and I can reproduce the issue.  Interestingly I get the following behaviour:

1. right-click outside the iframe, do inspect, open 'redux' tab: 

* the devtools don't load.

2. right-click _inside_ the iframe, choose 'redux devtools' -> 'open in a panel': 

* the devtools _do_ load in a separate window, and seem to work fine there.

So this isn't a fix, but it's at least a workaround while I dig deeper into it.

**Comment by PolarbearDK** [comment]
Hi,

Excellent timing! I have been working on another project, and just switched back to the application i originally experienced the problem with. 

The workaround is fine!

**Comment by e-schultz** [comment]
@PolarbearDK thanks for letting us know the workaround was fine. Going to close this issue for now, but if you need any other help - feel free to let us know.

**Comment by butlermd** [comment]
The workaround worked for me as well, until I updated to Chrome 84.

**Comment by khlevon** [comment]
Yes, it doesn't work on chrome 84, who can suggest a working variant?

**Comment by satheeshda** [comment]
This work around doesn't work for me on chrome V92, Please suggest some other work around
