### ISSUE TITLE
see if tassign is still relevant with later typescript versions

### ISSUE THREAD

**Issue by SethDavenport** [angular-redux/store#400]
object spread is supported now; check out how its typings work. If it makes sense, adjust the 'strongly typed reducers' article

**Comment by SethDavenport** [comment]
potentially deprecate tassign if that makes sense too

**Comment by e-schultz** [comment]
Quickly playing around in the TypeScript repl...

```ts
interface State {
  name: string;
  age: number;
  nickName: string;
}

let reducer = (state: State, action): State => {
  switch (action.type) {
    case 'ONE':
      return { ...state, x: 'y' }; // isn't an error - objects returned by spread don't care about extra params
    default:
      return state;
  }
  
}
```

```ts
interface State {
  name: string;
  age: number;
  nickName: string;
}

let reducer = (state: State, action): State => {
  switch (action.type) {
    case 'ONE':
        return { x: 'hi', name: '', age: 0, nickName: 'bob' } // this would complain due to 'x'  not being on State
    default:
      return state;
  }
  
}
```

Some discussion around this in the TypeScript repo - [#10727](https://github.com/Microsoft/TypeScript/issues/10727#issuecomment-300283560) - and some design notes around this behaviour is in [Design Meeting Notes, 12/16/2016](https://github.com/Microsoft/TypeScript/issues/12997)

There is also an issue for [Exact Types](https://github.com/Microsoft/TypeScript/issues/12936) which is in proposal that seems like it'd solve this. 

Someone linked to [spread operations with exact types](https://github.com/piotrwitek/react-redux-typescript-guide#spread-operation-with-exact-types-check-to-guard-against-excess-or-mismatched-props) - guide is geared towards react-redux, but demos using Partial's .

but the tl;dr I guess - until the Exact proposal gets implemented - still value in tassign.

**Comment by SethDavenport** [comment]
OK cool
