### ISSUE TITLE
persist store

### ISSUE THREAD

**Issue by yonathan06** [angular-redux/store#405]
### This is a...

* [X ] feature request

### What toolchain are you using for transpilation/bundling?

* [X ] angular/cli

## Adding a persist store (through localstorage)
Is there any plan on adding the ability of a persist store (for all reducers or a specific reducer)
Meaning saving the state in localstorage, and rehydrate the store on load.

something like this: [https://github.com/rt2zz/redux-persist](https://github.com/rt2zz/redux-persist
)
Thanks

**Comment by SethDavenport** [comment]
Yes - you can do this already!

One of the benefits of `angular-redux/store` is that we just wrap regular Redux: this means that Redux middlewares like https://github.com/rt2zz/redux-persist will work just fine with `angular-redux/store` as well.

You can just follow their init instructions, but lightly modified to account for Angular and `angular-redux/store`'s init steps:

```typescript
import {Component} from '@angular/core'
import {NgRedux} from '@angular-redux/store'
import {compose, applyMiddleware, createStore} from 'redux'
import {persistStore, autoRehydrate} from 'redux-persist'

// Your top-level app component
// (or wherever you're currently initializing angular-redux in your app)
@Component({/* ... */})
export class AppComponent {
  constructor(ngRedux: NgRedux<IAppState>) {
    // Configure your redux store exactly the same way as in the redux-persist
    // README file:
    const store = createStore(
      reducer,                          // your root reducer
      undefined,                      // initial state to be seeded into the store (e.g. for SSR)
      compose(
        applyMiddleware(...),  // '...' === Any redux middlewares you may be using
        autoRehydrate()));       // the `autoRehydrate` store enhancer.

    // Tell angular-redux about it.
    ngRedux.provideStore(store);
  }
}
```

Alternatively, if you're already using the `NgRedux.configureStore` convenience function, it would look like this, since `autoRehydrate` appears to be a store enhancer:

```typescript
@Component({/* ... */})
export class AppComponent {
  constructor(ngRedux: NgRedux<IAppState>) {
    ngRedux.configureStore(
      reducer,                          // your root reducer
      undefined,                      // initial state to be seeded into the store (e.g. for SSR)
      [ ... ],                               // '...' === Any redux middlewares you may be using
      [ autoRehydrate() ]);      // the `autoRehydrate` store enhancer.
  }
}
```

**Comment by SethDavenport** [comment]
There are a number of redux middleware/store-enhancer libraries that allow you to persist portions of state to local storage; if they work with regular Redux, they should work with us. I personally have used this one quite a bit: https://www.npmjs.com/package/redux-localstorage

**Comment by yonathan06** [comment]
Great, thanks!

**Comment by eaponiente** [comment]
this has been the solution I am looking for the last 2 days. great job @SethDavenport

**Comment by adamlubek** [comment]
autoRehydrate has been removed in newer versions of redux-persist, can someone post solution on how to setup redux-persist now with angular-redux?
