### ISSUE TITLE
6.4.1 breaks @select mocking

### ISSUE THREAD

**Issue by ajdaniel** [angular-redux/store#413]
### This is a...

* [ ] feature request
* [x] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [x] angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 6.10.2
Typescript Version: 2.3.4
Angular Version: 4.0.0
@angular-redux/store version: 6.4.1
@angular/cli version: (if applicable) 1.0.0
OS: MacOS

### Link to repo showing the issus
(optional, but helps _a lot_)

### Expected Behaviour:

Mocking Selectors and firing them should actually call all subscribers

```
progressStub = MockNgRedux.getSelectorStub(StateSelectors.getProgress);
progressStub.next({ steps: [], index: 0 });
```

### Actual Behaviour:

Subscribers are not being called

```
export class MyComponent implements OnInit {
    @select(StateSelectors.getProgress) progress$: Observable<CreateStreamProgress>;

    ngOnInit() {
        this.progress$.subscribe(progress => { ... }); // <-- not called
    }
}
```

### Additional Notes:
(optional)

**Comment by SethDavenport** [comment]
Taking a look

**Comment by SethDavenport** [comment]
I'm having some trouble reproducing this - I've posted a demo PR to our example-app with your component and test in it here: https://github.com/angular-redux/example-app/pull/38

**Comment by SethDavenport** [comment]
When I run `ng test` on that PR, I gest this output in Chrome:

<img width="1045" alt="screen shot 2017-05-31 at 9 09 20 am" src="https://cloud.githubusercontent.com/assets/4614141/26633336/0df69da8-45e1-11e7-9df0-9a2f592cb1f8.png">

As you can see, `subscribe` did in fact get called: that's what's printing 'I was called with ...' to the console.

What am I missing?

**Comment by ajdaniel** [comment]
I'll investigate further and get back to you as soon as I can @SethDavenport. Thank you for investigating

**Comment by SethDavenport** [comment]
Can you post the code for `StateSelectors.getProgress`? Just wondering if there's some boundary case there that I haven't tried.

**Comment by SethDavenport** [comment]
@gregkopp - thanks that does help. In your case what's happening is that `MockNgRedux.getSelectorStub('accountState')` is getting called with a different selector than `@select((state: AppState) => state.accountState) accountState$`

The two selectors evaluate to the same thing (the value of store.accountState), but that's not how
MockNgRedux works: MockNgRedux calls `.toString()` on the selector and uses that as a map key to match the selectorStubs to the `@select` calls in the app code. So it's seeing

`'accountState'` in one place and `'(state) => state.accountState'` in the other.

For the selectorStub to work, they need to match.  It works for `@select() accountState$` because when called with no args, `@select()` infers a selector from the property name (minus the `$`).

**Comment by ajdaniel** [comment]
Looks like I need to try my implementation again, I will get back to you

**Comment by SethDavenport** [comment]
@ajdaniel I was lazy with my implementation of `bug413test` - it never fails :)

You can verify if the functionality is working by looking in Chrome's javascript console for the karma results tab.  If the selector stub is working, you'll see:

```
START
I was called with Object
END
```

If it's not working, you'll see
```
START
END
```

I guess I can update the test to make it less confusing.

**Comment by gregkopp** [comment]
@SethDavenport Does this break AoT at runtime, or just in executing the tests?

That pattern is commonly used, right? Are all implementations of anonymous function selectors breaking AoT?

BTW, your suggestion did work, but your answer to the above may dictate the direction this app will take.

**Comment by ajdaniel** [comment]
@SethDavenport I realised after I said my last comment :( I've been tweaking your test and it still passes, but mine does not. If I debug my test and go into the `MockNgRedux.getSelectorStub` functionality, after it builds the string key and then looks for an existing selector stub, it never finds an existing one, but surely it should find the `@select` from the component?

![image](https://cloud.githubusercontent.com/assets/867941/26635036/5d5c7154-4610-11e7-88cc-fd2dd2dbf5a3.png)

**Comment by SethDavenport** [comment]
@gregkopp: It's at runtime.

Not sure what your toolchain is. But if it's @angular/cli, try this:

`ng serve`: builds and runs fine, but the bundles are unoptimized; you don't get ahead of time template compilation and browsers have to download the whole @angular/core libs which are not exactly light.

`ng serve --aot`: will give you some weird error and 'Function calls not supported'.

Typically unit tests don't use AoT at all so that's fine.

IIRC the constraint of Angular's AoT compiler is that anonymous arrow functions are fine except in the following specific cases:

* as static methods on a decorated class (`@Component`, `@Directive`, `@Injectable`, etc.)
* as arguments to property decorators.

In those cases, you have to pull them out and export them.  This is something that burned a lot of people (me included) who had codebases dating from before the introduction of AoT (circa Angular 2 rc5 IIRC).

Most codebases I've seen have moved to a model where the pull out their selector functions in to their own file(s) and export them; not only because of this but for selector re-use reasons as well.

**Comment by SethDavenport** [comment]
@ajdaniel so in your case `@select` is somehow getting the real `NgRedux` instance instead of `MockNgRedux`?

**Comment by SethDavenport** [comment]
Another random question - does `SharedModule` have `NgReduxModule` in it's imports array? I'm wondering if that's overriding the setup for MockNgRedux somehow.

**Comment by ajdaniel** [comment]
@SethDavenport it looks to be that way, yes. 

I couldn't find any occurrences of `NgRedux.instance`.

I had the same thought about Shared module, my failing tests import it, but `SharedModule` does not import `NgReduxModule`

`fakeStore` gives me instant access to the state via selectors, here's my code:

```
import { Injectable } from '@angular/core';
import { NgRedux } from '@angular-redux/store';
import { Observable } from 'rxjs/Rx';

export interface StoreState {
    ... some stuff
}

@Injectable()
export class Store {

    constructor(private ngRedux: NgRedux<StoreState>) {}

    select(selector: (StoreState) => any = store => store): any {
        return selector(this.ngRedux.getState());
    }

    selectAsync(selector: (StoreState) => any = store => store): Observable<any> {
        return this.ngRedux.select(selector);
    }

}
```

So of the failing tests that use `MockNgRedux` use both `SharedModule` and `Store` but not sure where the problem might be exactly?

**Comment by ajdaniel** [comment]
Somehow @angular-redux/store@6.4.1 breaks this but versions before are okay, there's something really subtle here

**Comment by ialibhay** [comment]
I'm actually getting the same problem. The first test using MockNgRedux passes successfully, but any subsequent test does not.

From a quick and dirty test, it seems that the correct MockNgRedux is used, but in the select decorator:

```javascript
function getter() {
   if (NgRedux.instance && !result) {
    result = NgRedux.instance.select(bindingKey, comparator);
  }
  return result;
}
```

The "result" variable is not being cleared for subsequent tests, so a new selection is never registered after "MockNgRedux.reset()" is called. The component then uses the previous selection, which the new call to "getSelectorStub" doesn't know about.

**Comment by ajdaniel** [comment]
So `result` just needs to be cleared in a `reset()`?

**Comment by SethDavenport** [comment]
@ialibhay yeah that makes sense. Thanks!

I'll try and hack up a fix tonight.

**Comment by SethDavenport** [comment]
Fixed PR up here: https://github.com/angular-redux/store/pull/414

@ajdaniel can you try `6.4.2-beta.0` and let me know if that fixes the issue for you? If so I'll push out 6.4.2 officially tomorrow.

**Comment by RichardMatsen** [comment]
I have similar symptoms to @ialibhay, i.e first test passes but second fails. I debugged into the selected values and 2nd test uses the store values set by 1st test, even though I .reset() and reload MockNgRedux in the 2nd test. Also (maybe obviously), if I fit() the 2nd test so it runs by itself, it passes.

Re versions, 
6.4.0 - tests pass
6.4.1- fails
6.4.2-beta.0 - fails

**Comment by ajdaniel** [comment]
I can confirm my tests fail in the exact same manner as 6.4.1

**Comment by SethDavenport** [comment]
OK Thanks

I've traced it down to what appears to be a packaging fail on my part. I'll post another version later this morning.

**Comment by SethDavenport** [comment]
@ajdaniel @ialibhay @RichardMatsen ...ok... give 6.4.2-beta.1 a try and let me know.

**Comment by ajdaniel** [comment]
@SethDavenport I can confirm that my tests now pass with 6.4.2-beta.1

**Comment by SethDavenport** [comment]
Perfect. I will release 6.4.2 shortly.

**Comment by SethDavenport** [comment]
Fixed in `@angular-redux/store@6.4.2`. Sorry for the disruption.

**Comment by ajdaniel** [comment]
@SethDavenport thank you for working on this and fixing. This is a great library and I am using it in earnest!

**Comment by ialibhay** [comment]
My tests also pass now. Although now I'm getting compile errors when compiling my project with the strict flag:

```
ERROR in /node_modules/@angular-redux/store/testing/observable-store.mock.ts (50,21): Function expression, which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in /node_modules/@angular-redux/store/testing/ng-redux.mock.ts (5,3): 'ObservableStore' is declared but never used.

ERROR in /node_modules/@angular-redux/store/testing/ng-redux.mock.ts (9,10): 'Reducer' is declared but never used.

ERROR in /node_modules/@angular-redux/store/testing/ng-redux.mock.ts (9,19): 'Action' is declared but never used.

ERROR in /node_modules/@angular-redux/store/testing/ng-redux.mock.ts (10,10): 'Observable' is declared but never used.

ERROR in /node_modules/@angular-redux/store/testing/ng-redux.mock.ts (12,10): 'ReplaySubject' is declared but never used.
```

**Comment by SethDavenport** [comment]
Yeah we should enable `strict` in our build process. Would you mind filing a separate issue for this?

**Comment by sbley** [comment]
Took me hours to find out my tests failed due to this bug. Thank you for fixing!
