### ISSUE TITLE
static property doesn't work with @select decorator and HMR

### ISSUE THREAD

**Issue by doronnac** [angular-redux/store#421]
### This is a...

* [ ] feature request
* [x ] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [ ] @angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [x ] Other

### Environment

NodeJS Version: 7.5.0
Typescript Version: 2.1.5
Angular Version: 4.0.1
@angular-redux/store version: 6.4.2
@angular/cli version: (if applicable)
OS: MacOS El Capitan

### Link to repo showing the issus
(optional, but helps _a lot_)

### Expected Behaviour:
component: @select() stuff$
template: {{stuff$ | async}} one-way binding should work after hot-reloading with HMR

### Actual Behaviour:
one way binding doesn't work after hot-reloading
this.stuff$ = ngRedux.select('stuff') does work as intended

### Stack Trace/Error Message:
Nothing

### Additional Notes:
(optional) My boilerplate is a slightly modified https://github.com/AngularClass/angular-starter.git
This bug was also reproduced on this boilerplate as-is, with HMR enabled (npm run start:hmr)

**Comment by SethDavenport** [comment]
I'm a bit behind on the state of HMR with Angular (I use it a lot with React). When you say "'@select` doesn't work" can you clarify? You mean you stop getting updates?

**Comment by doronnac** [comment]
@SethDavenport That's basically it, no updates are received after HMR

**Comment by SethDavenport** [comment]
OK - I'll try and get to this next week.

**Comment by SethDavenport** [comment]
Yeah so I can reproduce the issue - and it's likely because for performance / memory reasons `@select` causes a reference to the NgRedux instance to be cached. If HMR results in a new store instance being created, the `@selects` are still holding onto the old instance and don't fire when the new store changes.  Looking into how this can be improved.
