### ISSUE TITLE
getSelectorStub bug with 'state => state.select' pattern ??

### ISSUE THREAD

**Issue by rhday74** [angular-redux/store#425]
### This is a...

* [ ] feature request
* [x] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [x] @angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 6.11.0
Typescript Version: 2.3.4
Angular Version: 4.1.3
@angular-redux/store version: 6.4.5
@angular/cli version: (if applicable) 1.1.1
OS: OS X Sierra 10.12.5

### Expected Behaviour:

simple unit test of NgRedux.select behaves as expected

### Actual Behaviour:

Only seems to want to work when I use the 'state.someValue.someChildValue' syntax as opposed to the 'state => state.someValue.someChildValue' pattern

### Additional Notes:
I've attached what I'm seeing and maybe I'm just losing it but here goes.  I've got an Angular Service that exposes several selector methods to consumption by downstream components.  I'm not typically using the @select decorator (although it doesn't matter in this case apparently) but I was refactoring the unit tests for a particular Selector Service and came across some weird behavior.  Attached is a screenshot entitled NOT_WORKING_SELECTOR: 

![not_working_selector](https://user-images.githubusercontent.com/9594104/27059605-012ae7da-4f9d-11e7-96ce-be2658af722d.png)

which is how the code was originally written.  For whatever reason I had to modify the selector to match the pattern seen in attached screenshot WORKING_SELECTOR:

![working_selector](https://user-images.githubusercontent.com/9594104/27059606-012ebbb2-4f9d-11e7-9f21-d08cdfba8fc9.png)

You can see the test output (test is deliberately broken just to show that it's executing) with the wallaby.js logging in there for good measure. 

![wallaby_test_output](https://user-images.githubusercontent.com/9594104/27059604-012859b6-4f9d-11e7-8385-7ebfb42a6004.png) 

Is there something about using a lambda in there that mucks with getSelectorStub()??  My entire Store is made of Immutable data structures if that matters any.

**Comment by e-schultz** [comment]
@rhday74 - thanks for raising the issue. 

Looking into what's going on under the hood - and `getSelectorStub` is doing a `.toString()` on what is passed in for creating a mapping of selectors/observables.

Is there a chance that in your service and unit test, there is a difference in how you are providing the selector? for example - service is using the function, unit test is using the keyPath?

```ts
export class SomeService {
   someThing(): Observable<boolean> {
       return this.store.select(state=>state.navState.get('isPopped'))
// when storing selections, we do a .toString on this which ends up being
// "state => state.navState.get('isPopped')" as a string
   }
}

// in the unit test

it('should pop', ()=>{ 
    const selectorStub = MockNgRedux.getSelectorStub(['navState','isPopped'])
// when storing selections, we do a .toString on this which ends up being
// "navState,isPopped" as a string
})
```

So the selections collection that we use ends up being something like

```ts
selectons = {
    "state => state.navState.get('isPopped')":  { /* .... */},
    "navState,isPopped": { /* .... */ }
}
```

Could you verify if in your service `select` and in your mock `getSelectorStub` that the selector is being defined in a consistent way. 

If they are, and this is still an issue - I will look into this further.

**Comment by rhday74** [comment]
oh yeah sorry I forgot to mention that part.  the screenshots I included show the selector patterns as being different but no, if I use `state => state.navState.get('isPopped')` with both the service and with `getSelectorStub` it still doesn't work right unfortunately.  

I think you're on the right path though.  It doesn't matter how I define my selector pattern in the service, it's definitely how I pass the selector to the `getSelectorStub` method that matters.  If I try and use a lambda it just flat out won't work

**Comment by SethDavenport** [comment]
I tried it locally with a basic arrow function and it seems to be working - I wonder if there's some subtle difference in the two different places where the function is defined.

Normally people stick to PropertySelectors or PathSelectors for simple cases; and for cases where more complex functions are needed, they split them out into their own file in which case both the unit test and the code import the function and pass it by reference.

However you do seem to have hit a weird boundary case here.  Can you stick a `console.log((state => state.navState.get('isPopped')).toString())` in both locations and post the output?

**Comment by rhday74** [comment]
output appears to be the same in both spots `'function (state) { return state.navState.get('isPopped'); }'`

**Comment by rhday74** [comment]
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular/cli'],
        plugins: [
            require('karma-jasmine'),
            require('@angular/cli/plugins/karma'),

            // launchers
            require('karma-chrome-launcher'),
            require('karma-phantomjs-launcher'),

            // reporters
            require('karma-jasmine-html-reporter'),
            require('karma-mocha-reporter'),
            require('karma-coverage-istanbul-reporter')
        ],
        client: {
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        files: [
            { pattern: './src/test.ts', watched: false }
        ],
        preprocessors: {
            './src/test.ts': ['@angular/cli']
        },
        mime: {
            'text/x-typescript': ['ts', 'tsx']
        },
        coverageIstanbulReporter: {
            reports: ['html', 'lcovonly'],
            fixWebpackSourcePaths: true
        },
        angularCli: {
            environment: 'dev'
        },
        reporters: config.angularCli && config.angularCli.codeCoverage
            ? ['mocha', 'coverage-istanbul']
            : ['mocha', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['PhantomJS'],
        // browsers: ['ChromeHeadless'],
        singleRun: false
    });
};
```

that my `karma.conf.js` I'm using with the CLI...maybe something interesting in there

**Comment by SethDavenport** [comment]
OK yeah looks like istanbul is mangling the function.  I'm not sure there's a whole lot we can do about that. In general, inlining the lamba into `@select` will cause you problems with Angular's AoT anyway.

What I would suggest is either of the following AoT-safe, mock-happy alternatives:

## PathSelector

**Service:**
```typescript
// Note that this works with ImmutableJS too.
@select(['navState', 'isPopped']) isPopped$;

// ...
```

**Unit Test:**
```typescript
const stub = getSelectorStub(['navState', 'isPopped']);

// ...
```

## Exported FunctionSelector by Reference

**Service:**
```typescript
export const selectIsPopped = state => state.navState.get('isPopped');

// ...
@select(selectIsPopped) isPopped$;
```

**Unit Test:**
```typescript
import { selectIsPopped } from './wherever';

// ...

const stub = getSelectorStub(selectIsPopped);
```

**Comment by rhday74** [comment]
okay thanks for taking a look at it, I'll adjust the tests accordingly
