### ISSUE TITLE
ng build --prod --aot fails to compile because of function inside @select annotation

### ISSUE THREAD

**Issue by TimoWestland** [angular-redux/store#449]
### This is a...

* [ ] feature request
* [x] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [x] angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 6.9.5
Typescript Version: 2.4.2
Angular Version: 4.3.1
@angular-redux/store version: 6.5.7
@angular/cli version: 1.2.4 (global also 1.2.4)
OS: OS X Sierra 10.12.4

### Link to repo showing the issue
Private project for client, sorry. (I can share more parts of the code if required)

### Expected Behaviour:
To compile "ng build --prod --aot" successfully (ng --prod without aot produces the same error)
*note: ng build without the --prod or --aot flag compiles without errors.

### Actual Behaviour:
Failed to compile (see erros below)

### Stack Trace/Error Message:
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 29:11 in the original .ts file), resolving symbol MyaPersonalDataPage in /Users/timowestland/Documents/git-repos/yarden-angular-mijn/src/app/pages/personal-data/personal-data.page.ts

line 29 of personal-data.page.ts: _@select(s => !!s.session.token) loggedIn$: Observable<boolean>_

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/timowestland/Documents/git-repos/yarden-angular-mijn/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts

### Additional Notes:
This function composition used to work before i upgraded all my dependencies
@select(s => !!s.session.token) loggedIn$: Observable<boolean>

At that time i was using the following dependencies:
@angular: 2.4.8
@angular-cli: 1.0.0-beta.28.3
typescript: 2.1.6
@angular-redux/store: 5.1.2 (still called ng2-redux then)

I've found a workaround:
_this.loggedIn$ = this.ngRedux.select(s => !!s.session.token)_
Writting it like this makes the error go away

But I would definitely prefer to use the the annotation because it's cleaner and more consistent with the rest of my code. 

Any idea why the current combination of the dependencies doesn't allow this usage of the select annotation to work anymore?

If i look at https://github.com/angular-redux/store/blob/master/articles/select-pattern.md then this should still be supported.

@select(s => !!s.session.token) loggedIn$: Observable<boolean>

Thanks in advance!

**Comment by e-schultz** [comment]
Hi, 

Currently this is a limitation of the AoT compiler - hopefully one that can be fixed on their side. 

Basically, you need to export a function and have that be used in your select, for example

```ts
// I like co-locating my selectors along with my reducers, although this could be in the same file as your component 
export const loggedInSelector = (state) => !!state.session.token;

class MyComponent {
     @select(loggedInSelector) loggedIn$;
}
```

I will update the docs to reflect this - as it is something that does catch people off guard once they goto build their application with AoT enabled.

**Comment by TimoWestland** [comment]
Hi @e-schultz,

Thanks for your reply. Your solution is very simple and elegant so I can work with that for now.
I'll check again when an new version of the angular-cli-compiler is released. 

Thanks for your help. You can close this now if you want :)

**Comment by e-schultz** [comment]
Not a problem, glad I could help.
