### ISSUE TITLE
page navigation 

### ISSUE THREAD

**Issue by Raviraj20** [angular-redux/store#454]
# hi need a help can any one help me
i want to redirect to a next page on the click of the login button
in angular 2 project

**Comment by e-schultz** [comment]
Hi, 

Are you wanting to have the navigation happen after something in redux happens (action is dispatched, a certain state is hit?) - or just navigate on button click?

**Comment by e-schultz** [comment]
@Raviraj20 hi rav, since there hasn't been any activity on this I'll be closing the issue, if you need help / clarification please feel free to re-open with more details. Thanks

**Comment by Raviraj20** [comment]
Ok and thanks i have solved that Issue
