### ISSUE TITLE
Multiple Enhancers(DevToolsExtension and redux-localstorage) co-exist

### ISSUE THREAD

**Issue by enjoylifeqd** [angular-redux/store#460]
### usage question

### Version Info
angular/cli: 1.3.2
node: 8.2.1
os: linux x64
angular/animations: 4.3.3
angular/common: 4.3.3
angular/compiler: 4.3.3
angular/core: 4.3.3
angular/forms: 4.3.3
angular/http: 4.3.3
angular/platform-browser: 4.3.3
angular/platform-browser-dynamic: 4.3.3
angular/router: 4.3.3
angular/cli: 1.3.2
angular/language-service: 4.3.3
OS: ubuntu 16LTS

### Expected Behaviour:

DevToolsExtension and redux-localstorage can worked fine seperately , but configured both in  ngRedux.configureStore(), errors reported.

### Actual Behaviour:

![image](https://user-images.githubusercontent.com/13972132/29905002-3c6f2c02-8e4f-11e7-94b3-fd51d048b022.png)

### Additional Notes: Configurations
**My **root.reducer.ts** configuration.**

```ts
import { combineReducers } from 'redux';
import { itemReducer, SelectedItem} from './item.reducers';
_import persistState from 'redux-localstorage'_

export class IAppState {
 item?: SelectedItem;
};

export const rootReducer = combineReducers<IAppState>({
 itemReducer,
});

_export const itemEnhancers = [
    persistState('itemReducer', { key: 'itemReducer' })
  ];_
```

**My **App.module.ts** configruation**

```ts
//State Management
import { NgReduxModule, NgRedux, DevToolsExtension } from '@angular-redux/store';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
  ],
  providers: [
    itemsActions
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule {
  constructor(ngRedux: NgRedux<IAppState>,
              devTools: DevToolsExtension) {
             
              const middleware = [
              ];

               ngRedux.configureStore(
                  rootReducer,
                  {},
                  middleware, 
                  [...itemEnhancers,
                    devTools.isEnabled() ? [ devTools.enhancer() ] : []
                  ]); 
  }
}
```ts
### Thanks a in advance.

**Comment by e-schultz** [comment]
Hi, wondering if having a nested array for the store enhancers is causing the issue?  Maybe try 

```ts
const storeEnhancers =  devTools.isEnabled() ? [ ...itemEnhancers, devTools.enhancer() ] : [... ...itemEnhancers]
ngRedux.configureStore(rootReducer,{},middleware, storeEnhancers); 
```

**Comment by enjoylifeqd** [comment]
>  @`e-schultz`: Boss, please accept my knees(Chinglish), thanks for casting lights when I give up. It's working like a magic.
