### ISSUE TITLE
Trying to subscribe to stae - however getting undefined

### ISSUE THREAD

**Issue by LirazRom** [angular-redux/store#462]
I am trying to use the angular-redux/store (very nice framework)
however I get some error - seems as timing issue

in my module I have defined the store
`export class AppModule {
  constructor(ngRedux: NgRedux<IAppState>) {
    ngRedux.configureStore(reducer, InitialState, [createLogger()]);
  }
}`

and in the app.component i have created a breadcrumb component. the breadcrumb supposed to be subscribed to the store - in order to know which steps is in valid state , otherwise it is disabled.

so

`@Component({
  selector: 'app-navigation-bread-crumb',
  templateUrl: './navigation-bread-crumb.component.html',
  styleUrls: ['./navigation-bread-crumb.component.css']
})
export class NavigationBreadCrumbComponent implements OnInit {

  @Input() entries: IBreadCrumbEntry[] = [];
  @select('awsSteps') stepsValidation$: Observable<WizardStep[]>

  constructor(private router: Router) {}

  ngOnInit() {
    this.stepsValidation$.subscribe(steps => {
      if(steps) {
        steps.forEach(step => {
          let n = this.entries.find(entry => {
            return entry.name === step.name;
          })

          if(n) {
            n.valid = step.valid;
          }
        })
      }
    })
  }

  goToRoute(url: String) {
    this.router.navigate([url]);
  }

}`

and i am getting undefined as the steps
however in other component which is loading later - all is ok

this is the state object
`export interface IAppState {
  aws: AwsState,
  awsData: AwsData;
  awsSteps: WizardStep[]
}`

is there an option to wait for the store to be ready?

**Comment by e-schultz** [comment]
What value are you passing as `InitialState`? is steps always undefined - or just at the initial subscribe?

**Comment by LirazRom** [comment]
the InitialState has value in it. also i have tried to bind to other properties in the state and got undefined while other components which were activated later got data

**Comment by e-schultz** [comment]
Hrmm, could try:

```ts
this.stepsValidation$.filter(steps=>steps != undefined).// the rest
```

although without seeing how the reducers / state is being setup unclear to why that would be undefined at the start.

**Comment by e-schultz** [comment]
@LirazRom doing some issue house cleaning, as there has not been any activity on this issue - closing it for now. If you are still having issues, please feel free to re-open, or start another issue.

Thanks,

Evan
