### ISSUE TITLE
Fractal Stores Issue

### ISSUE THREAD

**Issue by adrianromanko** [angular-redux/store#463]
I'm using the Fractal Stores with @WithSubStore decorators. The main Redux store state is configured using ImmutableJS. The setIn() function call coming from the substore always overrides the main state with a plain object and this is crashing selectors that expecting to use an Immutable store.

The setIn(..) util needs to detect if we are using an immutable JS object otherwise it will always return a plain object even if the state is an ImmutableJS construct.

Needs a check for an Immutable Object
https://github.com/angular-redux/store/blob/master/src/utils/set-in.ts#L15

This works:
https://github.com/angular-redux/store/blob/master/src/utils/get-in.ts#L13

**Comment by adrianromanko** [comment]
@SethDavenport 
Could you advise on the fractal implementation.
The rootFractalReducer uses the setIn utility function.
```
return fractalKey && localReducer ?
      setIn(
        state,
        fractalPath,
        localReducer(
          getIn(state, fractalPath),
          action)) :
      state;
```
The setIn function should check if the selected state is an ImmutableJS construct and call the local .setIn or the ImmutableJS .setIn for you.

Thanks.

**Comment by SethDavenport** [comment]
@adrianromanko yes you're right. I'm a bit pressed for time at the moment but I'd be happy to review a PR if you're willing to submit one.

**Comment by Draccoz** [comment]
Anything happening with this issue? It affects me as well and kinda blocks my workflow. I'd be happy to make a PR myself, but I'm afraid I will not find the time in the near future.

**Comment by Draccoz** [comment]
OK that was much easier/faster than I thought it was. Could you please merge the PR in and release a version with that fix?

**Comment by SethDavenport** [comment]
I'll take a look later today.
