### ISSUE TITLE
What is the best practices to keep state and FormControl in sync?

### ISSUE THREAD

**Issue by flensrocker** [angular-redux/store#465]
### This is a...

* [x] usage question

### Environment

Typescript Version: 2.4.1
Angular Version: 4.3.1
@angular-redux/store version: 6.5.7
OS: Windows, ASP.NET Core

### Additional Notes:
I want to edit a field of the state and on the other hand initialise the form with the current state or load another value from a database. Which is the best way to keep the input and the state in sync without getting to much roundtrips of actions and listeners?

Currently my code looks like this:
```typescript
interface IAppState {
    field: string;
}

control: FormControl = new FormControl();

constructor(private store: NgRedux<IAppState>) {
    this.store.select<string>(["field"])
        .filter((value: string) => (this.control.value !== value))
        .subscribe((value: string) => {
            this.control.setValue(value);
        });

    this.control.valueChanges
        .map<any, string>((value: any) => `${value}`)
        .subscribe((value: string) => {
            let state: IAppState = this.store.getState();
            if (state.field !== value) {
                this._store.dispatch({ type: "SET_FIELD", payload: value });
            }
        });
}
```
I will only set the control's value if it's different from the current value and only dispatch the action, if the current state is different. It feels a bit noisy, esp. the test against the current state.

Is there a better way? Is it possible to move the dirty check inside the reducer and therefor not trigger the listeners?

**Comment by flensrocker** [comment]
It seems like I could remove the state-check, if don't emit the valueChanges-event on the setValue:
```typescript
this.control.setValue(value, { emitEvent: false });
```
but I think, the check of the state against the current control value should be in place?

**Comment by gregkopp** [comment]
I haven't tried this in a real application, and there are likely mistakes in here, but have you tried something like this?

I think the other option would to debounce the subscription to the control.valueChanges subscription to slow down excessive dispatch calls. Just an idea.

```
interface IAppState {
    field: string;
}

@select(state => state.field) field$: Observable<string>;
@dispatch() onSetField = (payload) => ({ type: 'SET_FIELD', payload: value });

control: FormControl = new FormControl();

ngOnInit() {

  this.field$.subscribe((value: string) => this.control.setValue(value));

  this.control.valueChanges
    .map<any, string>((value: any) => `${value}`)
    .subscribe(newValue => {
      this.field$
        .switchMap(currentValue => {
          if(currentValue != newValue) {
            this.onSetField(newValue);
          });
        });
      });
    });
}
```

**Comment by flensrocker** [comment]
Thank you for your input. Your code doesn't compile and I don't know, where you're heading, since the `switchMap` has to return a value and there is no `subscribe` on the `switchMap`.

A `debounce` wouldn't help me, because it won't prevent the useless roundtrip with the same value.

For now I have a dirty-check before the `control.setValue` against the current control-value and in my reducer, when I want to set the new field content. But if I get new insights with this, I will post an update.

**Comment by KSuttle-cng** [comment]
Wouldn't you just use https://github.com/angular-redux/form?

**Comment by flensrocker** [comment]
Because I didn't know of it. :)

I will evalute that package, thanks.
