### ISSUE TITLE
Problem with combine reducer.

### ISSUE THREAD

**Issue by luiscontrerasm** [angular-redux/store#475]
### This is a...

* [ ] feature request
* [ ] bug report
* [ X ] usage question

### What toolchain are you using for transpilation/bundling?

* [ X ] @angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 8.5.0
Typescript Version: 2.3.3
Angular Version: 4
@angular-redux/store version: 6.5.7
@angular/cli version: (if applicable) 1.3.0
OS: Ubuntu 16.04 (64bits)

### Link to repo showing the issus
(optional, but helps _a lot_)

### Actual Behaviour:

Im trying to combine reducers with the combine reducer function im an getting this error 

ERROR in /home/luis/Documentos/MLS/BoilerPlate/src/app/app.module.ts (107,28): Argument of type 'Reducer<{}>' is not assignable to parameter of type 'Reducer<AppStoreInterface>'.
  Type '{}' is not assignable to type 'AppStoreInterface'.
    Property 'layoutInterface' is missing in type '{}'.

### Additional Notes:
What is the problem and how can i fix it ?

I've been looking in the entire docs and found no example of how to to this.

**Comment by gregkopp** [comment]
Can you post your code or a repo URL?

**Comment by luiscontrerasm** [comment]
I Stop using the combine reducers function and build a custom one.
That was my solution.

**Comment by e-schultz** [comment]
you could do combineReducers<any> - although sounds like there was a type issue
