### ISSUE TITLE
ERROR in Error: Error encountered resolving symbol values statically.  when using @select

### ISSUE THREAD

**Issue by abductedMind** [angular-redux/store#476]
### This is a...

Conflict between production mode in the angular cli and the select pattern using a function.

When building in development mode there is no error. When building in production mode the following error occurrs:

"ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function..."

This does not throw an error:
@select(['uiState', 'signUpState', 'currentStep']) currentStep$: Observable<number>;

This does throw an error:
@select((s: IAppState) => s.uiState.signUpState.currentStep) currentStep$: Observable<number>;

* [ ] feature request
* [x] bug report
* [x] usage question

### What toolchain are you using for transpilation/bundling?

* [x] angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 6.11.3
Typescript Version: 2..4.3
Angular Version: 4.x
@angular-redux/store version: 6.5.7
@angular/cli version: 1.4.9
OS: Windows

### Link to repo showing the issus
(optional, but helps _a lot_)

### Expected Behaviour:
to compile and work.

### Actual Behaviour:
angular-cli  throws a compile error expressing that properties need to be statically evaluated. 

### Additional Notes:
(optional)

**Comment by e-schultz** [comment]
the angular compiler doesn't like it if you pass an anonymous/arrow function into a decorator. 

If you were to do 

```ts
export const getCurrentStep = (s: IAppState) => s.uiState.signUpState.currentStep

export class MyComponent {
  @select(getCurrentStep) currentStep$: Observable;
}
```

then it should work in AoT mode.
