### ISSUE TITLE
Support for Angular 5+

### ISSUE THREAD

**Issue by stefan-karlsson** [angular-redux/store#480]
### This is a...

* [x] feature request
* [ ] bug report
* [ ] usage question

### Additional Notes:
Currently this project does not support Angular 5.0.
Is there any pre-release that does?

What do we need to change to implement the support?

**Comment by e-schultz** [comment]
Hi,

Just put out a pre-release of v6.6.0-1 - this just updated the peer deps to include Angular 5, initial testing seems like it works without issue, although I don't have any large apps on V5 yet to fully test - any feedback is appreciated. 

There is also v7.0.0-2 - which updates the typings, and also uses the newest version of the angular compiler/etc, but produces metadata/builds that don't work with Angular 4.

**Comment by e-schultz** [comment]
v7 has now been published - if you have any issues upgrading feel free to let me know / raise an issue. 

Thanks for your patience.
