### ISSUE TITLE
NPM Warning

### ISSUE THREAD

**Issue by ghaddon** [angular-redux/store#488]
### This is a...

* [ ] feature request
* [ ] bug report
* [ x] usage question

I receive the following error message after installing an NPM component.

NPM WARN @angular-redux/store@6.5.7 requires a peer of @angular/core@^2.4.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

Does warning reflect an issue I need to address?

### What toolchain are you using for transpilation/bundling?

* [ *] @angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cdk: 5.0.0-rc0
angular/cli: 1.5.0
angular/flex-layout: 2.0.0-beta.10-4905443
angular/material: 5.0.0-rc0
angular-devkit/build-optimizer: 0.0.32
angular-devkit/core: 0.0.20
angular-devkit/schematics: 0.0.35
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.0
typescript: 2.6.1
webpack: 3.8.1

### Expected Behaviour:

Would like to see no errors.

### Stack Trace/Error Message:

npm WARN @angular-redux/store@6.5.7 requires a peer of @angular/core@^2.4.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

### Additional Notes:
nothing

**Comment by mengel188** [comment]
Hi just use @angular-redux/store@v6.6.0-1 it has updated peerDependencies and is working fine with angular 5.0.x - no breaking changes. You can also upgrade to @angular-redux/store@v7.0.0

**Comment by e-schultz** [comment]
v6.6.0 also has a full publish now available on NPM - the warnings should go away. If you run into any issues with working with this with angular 5, feel free to open another issue.

Thanks!
