### ISSUE TITLE
why are the releases of this repo are orderless? 

### ISSUE THREAD

**Issue by bunnyvishal6** [angular-redux/store#493]
why are the releases of this repo are orderless? why v6.6.0 releases after v7.0.0. It's so confusing.

**Comment by SMHFandA** [comment]
Maintaining previous version.

**Comment by bunnyvishal6** [comment]
Then If I download it with npm why do I get v6.6.0 instead of v8.0.0-1. Which one is latest? v6.6.0 or v8.0.0-1?

**Comment by SMHFandA** [comment]
http://joxi.net/Dr8R80gik5nQP2

You can install latest npm version by command:
```
$ npm install  @angular-redux/store@latest
```

If you need another version you can specify which one:

```
$ npm install  @angular-redux/store@8.0.0-1
```

**Comment by e-schultz** [comment]
v8 was an accidental publish.
v6 - continued support for Angular 4
v7 - Angular 5+

**Comment by e-schultz** [comment]
Although, I can see how it's confusing - I've deprecated the v8 releases, and did a minor bump of to v7.0.1 (no code changes) just so it'd have the latest-tag.

**Comment by bunnyvishal6** [comment]
Oh thank you @e-schultz
