### ISSUE TITLE
StaticInjectorError[NgRedux]

### ISSUE THREAD

**Issue by yonathan06** [angular-redux/store#502]
### This is a...

* [ ] feature request
* [x] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [x] `@angular/cli`
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 8.4.0
Typescript Version: 2.4.2
Angular Version: 5
@angular-redux/store version: 7.0.2
@angular/cli version: 1.6.3
OS: macOS 10.13.2

### Expected Behaviour:

App compiling properly

### Actual Behaviour:

StaticInjectorError[NgRedux]

### Stack Trace/Error Message:

```
ERROR Error: StaticInjectorError[NgRedux]: 
  StaticInjectorError[NgRedux]: 
    NullInjectorError: No provider for NgRedux!
    at _NullInjector.get (core.js:993)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveNgModuleDep (core.js:10878)
    at NgModuleRef_.get (core.js:12110)
    at resolveDep (core.js:12608)

View_AppComponent_Host_0 | @ | AppComponent_Host.ngfactory.js? [sm]:1
-- | -- | --
  | proxyClass | @ | compiler.js:14647
  | DebugContext_.logError | @ | core.js:15030
  | ErrorHandler.handleError | @ | core.js:1488
  | (anonymous) | @ | core.js:5683
  | ZoneDelegate.invoke | @ | zone.js:388
  | Zone.run | @ | zone.js:138
  | NgZone.runOutsideAngular | @ | core.js:4701
  | (anonymous) | @ | core.js:5683
  | ZoneDelegate.invoke | @ | zone.js:388
  | onInvoke | @ | core.js:4753
  | ZoneDelegate.invoke | @ | zone.js:387
  | Zone.run | @ | zone.js:138
  | (anonymous) | @ | zone.js:870
  | ZoneDelegate.invokeTask | @ | zone.js:421
  | onInvokeTask | @ | core.js:4744
  | ZoneDelegate.invokeTask | @ | zone.js:420
  | Zone.runTask | @ | zone.js:188
  | drainMicroTaskQueue | @ | zone.js:594
  | Promise resolved (async) |   |  
  | scheduleMicroTask | @ | zone.js:577
  | ZoneDelegate.scheduleTask | @ | zone.js:410
  | Zone.scheduleTask | @ | zone.js:232
  | Zone.scheduleMicroTask | @ | zone.js:252
  | scheduleResolveOrReject | @ | zone.js:868
  | ZoneAwarePromise.then | @ | zone.js:978
  | PlatformRef.bootstrapModule | @ | core.js:5569
  | (anonymous) | @ | main.ts:11
  | ../../../../../src/main.ts | @ | main.bundle.js:1962
  | __webpack_require__ | @ | inline.bundle.js:55
  | 0 | @ | main.bundle.js:1991
  | __webpack_require__ | @ | inline.bundle.js:55
  | webpackJsonpCallback | @ | inline.bundle.js:26
  | (anonymous) | @ | main.bundle.js:1

```

### Additional Notes:
My app.module (where NgRedux is imported)

```

import { NgReduxModule, DevToolsExtension, NgRedux } from "@angular-redux/store";

.
.
.

@NgModule({
  declarations: [
    AppComponent,
    ...
  ],
  imports: [...,
    NgReduxModule
  ],
  providers: [...],
  bootstrap: [AppComponent]
})

export class AppModule {
  constructor(private ngRedux: NgRedux<IAppState.AppState>,
    private devTools: DevToolsExtension) {

    let enhancers = [persistState(['user'])];
    if (devTools.isEnabled()) {
      enhancers = [...enhancers, devTools.enhancer()];
    }

    this.ngRedux.configureStore(
      rootReducer,
      IAppState.initialState,
      [],
      enhancers);
  }
}
```

Can't add NgRedux as a provider (gives an error), although I shouldn't do it.

**Comment by adrianromanko** [comment]
If you are using Angular 5+ where the Reflective Injector has been deprecated and the JIT compiler no longer accepts providers which depend on reflection. The method signature went from Provider[] to StaticProvider[].

You'll need to define a static provider for DevToolsExtension
Example: Before:

[
  DevToolsExtension,
]

After:

[
  {provide: DevToolsExtension, useClass: DevToolsExtension, deps: [ApplicationRef, NgRedux]},
]

**Comment by adrianromanko** [comment]
The Angular 5+ JIT compilation will fail for platform creation and providers for the JIT compiler.

https://github.com/angular-redux/store/blob/master/src/ng-redux.module.ts
...
@NgModule({
  providers: [
    **{provide: DevToolsExtension, useClass: DevToolsExtension, deps: [ApplicationRef, NgRedux]},** // add static provider
    { provide: NgRedux, useFactory: _ngReduxFactory, deps: [NgZone] },
  ],
})
export class NgReduxModule {}

**Comment by yonathan06** [comment]
@adrianromanko So the only solution is using AOT only, until this change will be applied?
I get an error when using AOT, is it related?
```
ERROR in Error during template compile of 'OpaqueToken'
Function calls are not supported in decorators but 'makeDecorator' was called in 'Injectable'
    'Injectable' calls 'makeDecorator'.
```

**Comment by yonathan06** [comment]
Fixed it - removed all `@select` decorators, and initialised the observable in the onInit method
