### ISSUE TITLE
Error on redux.dispatch

### ISSUE THREAD

**Issue by danieldaeschle** [angular-redux/store#519]
### This is a...

* [ ] feature request
* [X] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [X] @ angular/cli
* [ ] Custom @ ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 8.11.1
Typescript Version: 2.4.2
Angular Version: 5.0.0
@angular-redux/store version: 7.1.1
@angular/cli version: 1.7.4
OS: Ubuntu 16.04

### Expected Behaviour:
It should work :laughing: 

### Actual Behaviour:
This message on compiling:
```
ERROR in node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts(10,31): error TS2420: Class 'NgRedux<RootState>' incorrectly implements interface 'ObservableStore<RootState>'.
  Types of property 'dispatch' are incompatible.
    Type 'Dispatch<RootState>' is not assignable to type 'Dispatch<AnyAction>'.
      Type 'RootState' is not assignable to type 'AnyAction'.
node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts(37,33): error TS2344: Type 'RootState' does not satisfy the constraint 'Action<any>'.
node_modules/@angular-redux/store/lib/src/components/root-store.d.ts(18,24): error TS2344: Type 'RootState' does not satisfy the constraint 'Action<any>'.
src/app/actions/note.ts(15,31): error TS2345: Argument of type '{ type: string; payload: Note; }' is not assignable to parameter of type 'IAppState'.
  Object literal may only specify known properties, and 'type' does not exist in type 'IAppState'.
src/app/actions/note.ts(19,31): error TS2345: Argument of type '{ type: string; payload: Note; }' is not assignable to parameter of type 'IAppState'.
  Object literal may only specify known properties, and 'type' does not exist in type 'IAppState'.
src/app/components/notedesk/notedesk.component.ts(2,32): error TS2307: Cannot find module '../shared/article.service'.
src/app/components/notedesk/notedesk.component.ts(3,25): error TS2307: Cannot find module '../shared/models/article'.
```

### Additional Notes:
![image](https://user-images.githubusercontent.com/30751516/39084419-05bfae46-4576-11e8-9735-74f4f7b73dfa.png)
![image](https://user-images.githubusercontent.com/30751516/39084423-0ecd0740-4576-11e8-837b-94145f39aa40.png)
![image](https://user-images.githubusercontent.com/30751516/39084426-1c14a08e-4576-11e8-881f-c6f95a1fc3f1.png)

Message transalted from german:
```
The argument of type "{ type: string; payload: Note; }" cannot be assigned to the "IAppState" type parameter.
  The object literal can only specify known properties, and "type" is not available in the "IAppState" type.
```

**Comment by danieldaeschle** [comment]
https://github.com/noteslab/web/tree/redux

**Comment by danieldaeschle** [comment]
Updated to newest angular - still same error

**Comment by depe6** [comment]
Same thing for me :(

**Comment by fredrik-macrobond** [comment]
Are you all using Redux 4.0?

**Comment by danieldaeschle** [comment]
Newest Version. Should be 4.0

**Comment by mythos0** [comment]
Same problem here. Only downgrade of Redux to v3.7.2 fixes the issue.

**Comment by LandSprutte** [comment]
Downgraded to Redux v3.7.2 from Redux 4. I'm using  "@angular-redux/store": "7", but still had the same problem. Though when I combined my reducers, I had to specify the IAppState in order for it to work.

export const rootReducer = combineReducers<IAppState>({
    common: commonReducer,
});

**Comment by ethanmick** [comment]
Same problem here.

**Comment by christinakayastha** [comment]
PR to fix this issue: #522 

In the mean time I've been just updating the respective .d.ts with `dispatch: Dispatch<AnyAction>`

**Comment by akashseth31** [comment]
Working the first time on Redux with angular and facing the same issue. Any help?

**Comment by danieldaeschle** [comment]
@akashseth31 it is a bug

**Comment by danieldaeschle** [comment]
PR isn't merged yet.

**Comment by kyyash** [comment]
Any ETA or any workaround ? Please advise.

**Comment by danieldaeschle** [comment]
Use ngrx/store

**Comment by kyyash** [comment]
i want to use it in conjunction with @angular-redux/form.

**Comment by danieldaeschle** [comment]
Then you have to wait for the fix or downgrade redux to version v3.7.2 which has already been said in this issue.

**Comment by kyyash** [comment]
if we use angular-redux/store and angular-redux/form, how to we downgrade redux alone when using npm from angular cli ?

**Comment by zinderud** [comment]
also add
    "@types/redux": "3.6.0",

**Comment by SethDavenport** [comment]
Redux 4 support is included in @angular-redux/store@9

**Comment by Riccardo-Andreatta** [comment]
I still have this same issue when upgrading my project from Angular 6 to Angular 7. The only difference is that it is complaining because of the incorrect implementation:
```
ERROR in node_modules/@angular-redux/store/lib/src/components/ng-redux.d.ts(10,31): error TS2420: Class 'NgRedux<RootState>' incorrectly implements interface 'ObservableStore<RootState>'.
  Property '[Symbol.observable]' is missing in type 'NgRedux<RootState>' but required in type 'ObservableStore<RootState>'.
```

I have the current packages installed:
```
        "@angular-redux/store": "^9.0.0",
        ...
        "@angular/core": "~7.2.15",
        ...
        "redux": "^4.0.1",
        "redux-devtools-extension": "^2.13.8",
        ...
```

What am I missing?
