### ISSUE TITLE
Error:NgRedux<RootState>' incorrectly implements interface 'O bservableStore<RootState>'

### ISSUE THREAD

**Issue by pucheoswaldo** [angular-redux/store#530]
### This is a...

* [ ] feature request
* [x] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [x] @angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 8.9.4
Typescript Version: 2.7.2
Angular Version: 6.0
@angular-redux/store version: 7.1.1
version: (if applicable)
OS: Windwows

### Link to repo showing the issus
(optional, but helps _a lot_)

### Stack Trace/Error Message:
![image](https://user-images.githubusercontent.com/8845581/40519498-c83a0008-5f8d-11e8-9ad2-ea8988902b44.png)

### Additional Notes:
(optional)

**Comment by wtho** [comment]
Version 9.0.0 with the fix is out already, but not yet published on npm.

**Comment by SethDavenport** [comment]
9.0.0 just released.
