### ISSUE TITLE
 tslib__WEBPACK_IMPORTED_MODULE_0__

### ISSUE THREAD

**Issue by michelLammensSmart** [angular-redux/store#535]
### This is a...

* [ ] feature request
* [ *] bug report
* [* ] usage question

### What toolchain are you using for transpilation/bundling?

* [* ] @angular/cli
* [x] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 8.11.3
Typescript Version:2.7.2
Angular Version:6.0.8
@angular-redux/store version:^9.0.0
@angular/cli version: (if applicable) : 6.0.8
OS:linux x64

### Expected Behaviour:
 @select() user; return => object user;

### Actual Behaviour:

 @select() user; return => tslib__WEBPACK_IMPORTED_MODULE_0__ is not defined

### Stack Trace/Error Message:
"ReferenceError: tslib__WEBPACK_IMPORTED_MODULE_0__ is not defined

### Additional Notes:
ts config:

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

**Comment by wtho** [comment]
Can you post the whole file where you used the `@select` in? Seems like you are not using it inside a component, and therefore `this` is not available.

`@select` is a typescript decorator that will execute some code when the class initializes. It is meant to decorate a field inside an Angular Component.

**Comment by lammensmichel** [comment]
https://github.com/lammensmichel/smartdeskbe/blob/master/src/app/smart-bar/smart-bar.component.ts
