### ISSUE TITLE
@subscribe decorator

### ISSUE THREAD

**Issue by e-schultz** [angular-redux/store#88]
Decorator that is similar to `@select`, but will also do the subscription instead of exposing the observable. 

``` js
@Component({
template: `{{counter$ | async}} - {{counter}}`
})
export class MyComponent {
  @select('counter') counter$;
  @subscribe('counter') counter;
}
```

instead of doing

``` js
@Component({
template: `{{counter$ | async}} - {{counter}}`
})
export class MyComponent {
  @select('counter') counter$;
  counterSub;
    ngOnInit() {
    this.counterSub = this.counter$.subscribe(n=>this.counter=n);
  }
  ngOnDestroy() { 
    this.counterSub.unsubscribe();    
  }
}
```

think I'd rather stick with just @select for now, but open to feedback/discussion on this.

**Comment by kosz** [comment]
what about @selectAndSubscribe ?

**Comment by SethDavenport** [comment]
I feel like @select removes the need for subscribe 99% of the time?

**Comment by SethDavenport** [comment]
I think this is probably overkill. Closing for now; feel free to reopen if you disagree.

**Comment by dagstuan** [comment]
I would like this to be honest. A lot of the times I need access to the current value of an observable in my model, as well as using the observable in the template. a `@selectAndSubscribe` decorator which automatically unsubscribes on destroy would be perfect for those use cases.

**Comment by SethDavenport** [comment]
OK. Reopening, we'll give it some more thought.

**Comment by gsans** [comment]
I think the async pipe does the subscribe and unsubscribe for you already
under the hood. No need for the extra code or decorator.

**Comment by dagstuan** [comment]
In the template AsyncPipe does the job @gsans. But if you want the current value in the model `.ts` as well you'd need two subscriptions, one for the template (AsyncPipe) and another for the model. And you would need to implement `ngOnDestroy` to clear the model subscription. Hence `@selectAndSubscribe` would be nice in some cases :)

**Comment by gsans** [comment]
I see. Then maybe you should replace the async pipe in the template with a
reference to the model instead?

**Comment by dagstuan** [comment]
Yup, but you'd still need to remember to unsubscribe. Its not that this feature is "needed" for ng2-redux to be usable, it would just be nice to have :)

**Comment by gsans** [comment]
Sounds good.

**Comment by SuperiorJT** [comment]
Has there been any progress on this? Currently working on an app where this could save us a lot of code. Currently, I have to make a container for a login form and binding the properties to the form component is very tedious and looks messy. Unless there is a better way to do it, this would help out a lot.

**Comment by dagstuan** [comment]
@SuperiorJT I made a really rough implementation of it, basically just copying the `@select`-decorator and rebinding `ngOnDestroy` on the component that selects something to do the unsubscribe. It works for my purposes, but it's not pretty and I havent really tested it well enough to PR it to this project yet. However, if you still want to check it out its here: https://gist.github.com/dagstuan/0a49e60135abb9861c758b18b1fdf00e

**Comment by SuperiorJT** [comment]
@dagstuan This actually works really well. Thanks!

**Comment by e-schultz** [comment]
Sorry for not keeping up on this, been pretty busy. 

Thinking of starting to break things out into their own modules, and maybe having things published under `@ng2-redux/X`

Not opposed to creating a new repo for this under the ng-redux org.

Appreciate the community input/feedback on this and would like to get more transparent on roadmap/philosophy/etc and make it easier for people to get involved and contribute.
